### ISSUE TITLE
Update the submission service configuration with MongoDb connection

### ISSUE THREAD

**Issue by danyloid** [flam-flam/dev-stack#2]
#### Acceptance

- When running the composed image `submission` service should be able to connect to the MongoDb
- README should be updated with additional configuration values required by `submission` service

#### Notes
This issue depends on https://github.com/flam-flam/submission-service/issues/7 completion

**Comment by danyloid** [comment]
@timberhill I've started this one, and started getting ideas, wanted to quickly align on few things. 

> Obligatory disclaimer: I am treating this repo purely as a dev environment setup & assuming that `compose\docker-compose.yaml` will not be used for actual deployment. 

#### .env
Is there any value in not having the default `.env` file in the repo ?

We can exclude sensitive secrets, however I don't see value in obscuring the Mongo credentials (as long as we don't use the same ones for actual deployment when we get to it). Does this make sense ? 

#### Makefile
Do we need to specify the `.env` file explicitly, e.g. `--env-file ./env.env` in the `up` command definition ? 
I have to admit that I was too lazy to set it up on Windows, and I was using shell commands directly, so I could have missed some extra magic. 

#### Extra tools
We could use [mongo-express](https://github.com/mongo-express/mongo-express) to provide a convenient way to look into the DB without using `mongosh`. It is [fairly easy to add](https://hub.docker.com/_/mongo)

**Comment by danyloid** [comment]
Assuming we're in agreement, I could go ahead and make these changes as part of the ticket implementation

**Comment by timberhill** [comment]
.env is in .gitignore to prevent people from committing secrets to the repo. But we could have a example.env of course

Not sure about where the .env is set explicitly. I think that docker compose uses a file called .env by default though.

A DB browser sounds hella nice, yes!

**Comment by danyloid** [comment]
@timberhill I've noticed that it is in `.gitignore`, was questioning whether it should be. However that is fair, have not considered the risk of accidentally committing secrets.
Will add and `example.env` then. 
One more thing - I am not considering `MONGO_INITDB_ROOT_USERNAME` & `MONGO_INITDB_ROOT_PASSWORD` (and `MONGO_CONNECTION_STRING` that I am about to add) to be sensitive values, do you agree ? 


Regarding the `.env` file - I believe it does not do that on Windows by default. 
If I don't specify the file explicitly - I'm getting the following output: 
```
PS C:\Storage\development\flam-flam\dev-stack> docker compose -f compose/docker-compose.yaml up  -d
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"REDDIT_CLIENT_ID\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"REDDIT_CLIENT_SECRET\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"DISPATCHER_BRANCH\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"COMMENT_BRANCH\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_CONNECTION_STRING\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_INITDB_ROOT_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_INITDB_ROOT_USERNAME\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_INITDB_ROOT_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_CONNECTION_STRING\" variable is not set. Defaulting to a blank string."
time="2023-03-22T21:28:12+01:00" level=warning msg="The \"MONGO_INITDB_ROOT_USERNAME\" variable is not set. Defaulting to a blank string."
[+] Running 5/0
 - Container compose-comment-1        Running                                                                                                                                                                                                                                                                                                                                                                0.0s
 - Container compose-mongodb-1        Running                                                                                                                                                                                                                                                                                                                                                                0.0s
 - Container compose-submission-1     Running                                                                                                                                                                                                                                                                                                                                                                0.0s 
 - Container compose-dispatcher-1     Running                                                                                                                                                                                                                                                                                                                                                                0.0s 
 - Container compose-mongo-express-1  Started            
``` 
That is not the case when I use `docker compose -f compose/docker-compose.yaml --env-file ./.env up -d`
Could you check if the above runs properly on linux ? If so - we could just specify file explicitly regardless of the OS. 

DB browser is settled then :)

**Comment by timberhill** [comment]
Yes, mongo creds are not sensitive, all good. This is only for local development. Any secrets will be set in kubernetes secrets and mounted onto a pod in any kind of "production" use.

Setting the .env file explicitly works on linux, all good!

**Comment by danyloid** [comment]
And here goes the PR: https://github.com/flam-flam/dev-stack/pull/3
Ideally https://github.com/flam-flam/submission-service/pull/10 should be merged first though
